=pod

=head1 NAME

SeTTY - set terminal properties

=head1 USAGE

setty [COMMAND]

=head1 COMMANDS

    alternate  use the alternate screen buffer
    backspace  toggle if the backspace key should send BS or DEL
    columns    toggle 132/80 columns mode
    reverse    toggle reverse video
    scrollbar  toggle scrollbar visibility
    scrollkey  scroll to bottom when key is pressed
    ttyscroll  scroll to bottom on TTY output
    wrap       toggle wraparound mode.

=head1 OPTIONS

    --help     show the help and exit
    --man      show the manual and exit
    --version  show version info and exit

=head1 ENVIRONMENT

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 CONTRIBUTORS

None required yet.

=head1 REPORTING BUGS

Report bugs and/or feature requests to <m@japh.se>, on L<rt.cpan.org>
or L<http://github.com/trapd00r/SeTTY/issues>.

=head1 COPYRIGHT

Copyright 2011 the B<SeTTY> L</AUTHOR> and L</CONTRIBUTORS> as
listed above.

=head1 LICENSE

This application is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=head1 SEE ALSO

L<urxvt(7)>

L<urxvt(1)>

L<console_codes(4)>

L<ctlseq|http://devel.japh.se/App-SeTTY/doc/ctlseq.txt>

=cut
