#!/usr/bin/perl
use strict;
#use warnings FATAL => 'all';
my  $APP     = 'SeTTY';
our $VERSION = '0.024';

my $options;

if(!@ARGV) {

  print << "...";
$APP v$VERSION
Usage: $APP [COMMAND]

...

  for my $option(sort(keys(%{ $options }))) {
    print "\n";

    printf("\e[1m$option\e[m - %s\n", $options->{ $option }->{description});

    printf("  set: %s\n", $options->{ $option }->{desc_set});
    printf("reset: %s\n", $options->{ $option }->{desc_reset});
  }
  exit;
}

my $action = shift;

die "No such option\n" if not exists( $options->{ $action } );

print $options->{ $action }->{command};


BEGIN {
  $options = {
    scrollbar  => {
      command     => "\e[?30t",
      description => 'toggle scrollbar visibility',
    },
    columns    => {
      command     => "\e[?3t",
      description => 'column mode',
      desc_set    => 'use a 132 column screen',
      desc_reset  => 'use a 80 column screen',
    },
    reverse    => {
      command     => "\e[?5t",
      description => 'toggle reverse video',
      desc_set    => 'make the screen white with black characters',
      desc_reset  => 'make the screen black with white characters',
    },
    wrap       => {
      command     => "\e[?7t",
      description => 'toggle wraparound mode.',
      desc_set    => 'autowrap at EOL (default)',
      desc_reset  => 'no wrapping',
    },
    backspace  => {
      command     => "\e[?67t",
      description => 'backspace/delete',
      desc_set    => 'backspace sends BS',
      desc_reset  => 'backspace sends DEL',
    },
    ttyscroll  => {
      command     => "\e[?1010t",
      description => 'scroll to bottom on TTY output',
      desc_set    => 'scroll to bottom on TTY output',
      desc_reset  => 'do not scroll to bottom on TTY output',
    },
    scrollkey  => {
      command     => "\e[?1011t",
      description => 'scroll to bottom on keypress',
      desc_set    => 'scroll to bottom on keypress',
      desc_reset  => 'do not scroll to bottom on keypress',
    },
    alternate  => {
      command     => "\e[?1049t",
      description => 'alternate screen mode',
      desc_set    => 'use alternate screen buffer',
      desc_reset  => 'use normal screen buffer',
    },
    jumpscroll => {
      command     => "\e[?4t",
      description => 'scrolling mode',
      desc_set    => 'scroll at a maximum rate of six lines/sec',
      desc_reset  => 'jump one line at a time',
    },
    vt52       => {
      command     => "\e[2t",
      description => 'ANSI/VT52 mode',
      desc_set    => 'Only ANSI compatible escape sequences recognized',
      desc_reset  => 'Only VT52 compatible escape sequences recognized',
    },
    cursor     => {
      command     => "\e[?25t",
      description => 'text cursor enable mode',
      desc_set    => 'visible',
      desc_reset  => 'invisible',
    },
  };
}

=pod

=head1 NAME

SeTTY - set terminal properties

=head1 USAGE

setty [COMMAND]

=head1 COMMANDS

    alternate   alternate screen mode
    backspace   backspace/delete
    columns     column mode
    cursor      text cursor enable mode
    jumpscroll  scrolling mode
    reverse     toggle reverse video
    scrollbar   toggle scrollbar visibility
    scrollkey   scroll to bottom on keypress
    ttyscroll   scroll to bottom on TTY output
    vt52        ANSI/VT52 mode
    wrap        toggle wraparound mode.

=head1 OPTIONS

    --help     show the help and exit
    --man      show the manual and exit
    --version  show version info and exit

=head1 ENVIRONMENT

=head1 AUTHOR

  Magnus Woldrich
  CPAN ID: WOLDRICH
  magnus@trapd00r.se
  http://japh.se

=head1 CONTRIBUTORS

None required yet.

=head1 REPORTING BUGS

Report bugs and/or feature requests to <m@japh.se>, on L<rt.cpan.org>
or L<http://github.com/trapd00r/SeTTY/issues>.

=head1 COPYRIGHT

Copyright 2011 the B<SeTTY> L</AUTHOR> and L</CONTRIBUTORS> as
listed above.

=head1 LICENSE

This application is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=head1 SEE ALSO

L<urxvt(7)>

L<urxvt(1)>

L<console_codes(4)>

L<ctlseq|http://devel.japh.se/App-SeTTY/doc/ctlseq.txt>

=cut
